spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    h2:
      console:
        enabled: true


management:
  # Actuator management settings used for local diagnostics; tighten before production.
  endpoint:
    env:
      show-values: always  # Include environment variable values in the /actuator/env endpoint.
    configprops:
      show-values: always  # Include property values in the /actuator/configprops endpoint.
  endpoints:
    web:
      exposure:
        include: "*"  # Expose every actuator endpoint over HTTP for local inspection.
